### PR TITLE
Update to whitelist PDFium

### PR DESCRIPTION
**Pull request by simonhong**
Issue: https://github.com/brave/brave-browser/issues/3846

### CODE REVIEW

**Comment by simonhong** [comment]
cc @bsclifton I can't edit reviewer/assignees list in this repo.

**Comment by bsclifton** [comment]
@pilgrim-brave @bbondy anything needed after the merge? 

When I did the PDF.js removal code, it looked like all we needed to do was update `DEPS` file in `brave-core`. Can you confirm?

**Comment by bbondy** [comment]
just noting that this will put it on the whitelist for all channels that use this whitelist / blacklist. 
I don't think that will cause any problems but just making sure @pilgrim-brave ?

**Comment by pilgrim-brave** [comment]
AFAIK users can't install PDFium manually, so this should be fine.

**Comment by bsclifton** [comment]
@bbondy should only take effect (AFAIK) if `DEPS` gets updated for other channels, right? When asking above, I couldn't remember if this gets packaged with the CRX packaging... I don't think it is, since it's called out in `DEPS` (doesn't show in brave://components/ either, so I think we're good)

**Comment by bbondy** [comment]
I think it's used in the local files brave/brave-core-crx-packager, so that means 1 extension for all channels. It's ok though.

**Pull request merged**
